version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "ftm_server"
    restart: always
    depends_on:
      - mysql
      - redis
      - nginx
    volumes:
      - ./docker_conf.py:/ftm/backend/app/core/conf.py
    networks:
      ftm_network:
        aliases:
          - ftm_backend_server
    command: supervisord -c supervisor.conf

  mysql:
    image: mysql:8.0.29
    ports:
      - "3306:3306"
    container_name: "mysql"
    restart: always
    environment:
      MYSQL_DATABASE: ftm
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    volumes:
      - /var/lib/mysql
    networks:
      - ftm_network

  redis:
    image: redis:6.2.7
    ports:
      - "6379:6379"
    container_name: "redis"
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /var/lib/redis
    networks:
      - ftm_network

  nginx:
    image: nginx
    ports:
      - "8000:80"
    container_name: "nginx"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - ftm_network

networks:
  ftm_network:
    driver: bridge