version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "ftm-server"
    restart: always
    depends_on:
      - mysql
      - redis
      - nginx
    networks:
      ftm-network:
        aliases:
          - ftm_backend_server
    command: supervisord -c supervisor.conf

  mysql:
    image: mysql:8.0.29
    ports:
      - "3306:3306"
    container_name: "mysql"
    restart: always
    environment:
      MYSQL_DATABASE: ftm
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    volumes:
      - /var/lib/mysql
    networks:
      - ftm-network

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"
    container_name: "redis"
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /var/lib/redis
    networks:
      - ftm-network

  nginx:
    image: nginx
    ports:
      - "8000:8000"
    container_name: "nginx"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - ftm-network

networks:
  ftm-network:
    driver: bridge