-- upgrade --
ALTER TABLE `user` DROP COLUMN `creator`;
ALTER TABLE `user` DROP COLUMN `modifier`;
ALTER TABLE `user` MODIFY COLUMN `updated_time` DATETIME(6) NOT NULL  COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6);
ALTER TABLE `user` MODIFY COLUMN `created_time` DATETIME(6) NOT NULL  COMMENT '注册时间' DEFAULT CURRENT_TIMESTAMP(6);
-- downgrade --
ALTER TABLE `user` ADD `creator` VARCHAR(32);
ALTER TABLE `user` ADD `modifier` VARCHAR(32);
ALTER TABLE `user` MODIFY COLUMN `updated_time` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6);
ALTER TABLE `user` MODIFY COLUMN `created_time` DATETIME(6) NOT NULL  DEFAULT CURRENT_TIMESTAMP(6);
