version: "3.8"

networks:
  ftm_network:
    driver: bridge

volumes:
  ftm_mysql:
  ftm_redis:
  ftm_static:

services:
  app:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: "ftm_server"
    restart: always
    depends_on:
      - ftm_mysql
      - ftm_redis
    volumes:
      - ftm_static:/ftm/backend/app/static
    networks:
      ftm_network:
        aliases:
          - ftm_backend_server
    command:
      - bash
      - -c
      - |
        wait-for-it -s ftm_mysql:3306 -s ftm_redis:6379 -t 300
        supervisord -c /ftm/deploy/supervisor.conf

  mysql:
    image: mysql:8.0.29
    ports:
      - "3306:3306"
    container_name: "ftm_mysql"
    restart: always
    environment:
      MYSQL_DATABASE: ftm
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    volumes:
      - ftm_mysql:/var/lib/mysql
    networks:
      - ftm_network
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --lower_case_table_names=1

  redis:
    image: redis:6.2.7
    ports:
      - "6379:6379"
    container_name: "ftm_redis"
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ftm_redis:/var/lib/redis
    networks:
      - ftm_network

  nginx:
    image: nginx
    ports:
      - "8000:80"
    container_name: "ftm_nginx"
    restart: always
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ftm_static:/www/ftm/backend/app/static
    networks:
      - ftm_network
